devices([
  "Screenshot-iPhone16Pro",
  "Screenshot-iPhone16ProMax",
  "Screenshot-iPadPro13M5"
])

languages(["en-GB"])

scheme("FuelFinder")
project("FuelFinder.xcodeproj")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)

# Only run screenshot tests
launch_arguments(["--uitesting"])
